---
- name: Обновление Git и DVC
  hosts: mlserver
  become: yes
  become_user: max

  tasks:
    - name: Получить изменения из Git
      ansible.builtin.git:
        repo: git@github.com:MaxAvgae/mlops2_project_1.git
        dest: /home/max/mlops2_project_1
        accept_hostkey: true
        key_file: /home/max/.ssh/is_rsa

    - name: Запустить DVC repro
      ansible.builtin.shell:
        cmd: dvc repro
        chdir: /home/max/mlops2_project_1

    - name: Добавить и зафиксировать изменения в Git
      ansible.builtin.command:
        cmd: git commit -am 'expr'
        chdir: /home/max/mlops2_project_1

    - name: Отправить в Git
      ansible.builtin.shell:
        cmd: git push
        chdir: /home/max/mlops2_project_1

    - name: Отправить в DVC
      ansible.builtin.shell:
        cmd: dvc push
        chdir: /home/max/mlops2_project_1

